import { Button } from "../generic/button.slint";

export component ControlBar inherits HorizontalLayout {
    
	property <bool> timerOn: false;
	
    callback buttonPressed(string);
    spacing: 15px;
	
	alignment: stretch;

    Button {
        button-color: #36548b;
        border-radius: 18px;
        text: "";
        id: "stop";
        font-size: 25px;
            
        Image {
            source: @image-url("../svg/stop--filled.svg");
            colorize: white;
        }

        clicked => {
            buttonPressed(self.id);
        }

    }
            
    Button {
        button-color: #36548b;
        border-radius: 18px;
        text: "";
        id: timerOn ? "pause" : "play";
        font-size: 25px;

        Image {
            source: timerOn ? @image-url("../svg/pause--outline--filled.svg") : @image-url("../svg/play--filled.svg");
            colorize: white;
        }

        clicked => {
            buttonPressed(self.id);
			timerOn = !timerOn;
        }

    }

}