import { Button } from "../generic/button.slint";

export component ControlBar inherits HorizontalLayout {
    
    callback buttonPressed(string);

    spacing: 15px;

    Button {
        button-color: #36548b;
        border-radius: 18px;
        text: "";
        id: "stop";
        font-size: 25px;
            
        Image {
            source: @image-url("../svg/stop--filled.svg");
            colorize: white;
        }

        clicked => {
            buttonPressed(self.id);
        }

    }
            
    Button {
        button-color: #36548b;
        border-radius: 18px;
        text: "";
        id: "play";
        font-size: 25px;

        Image {
            source: @image-url("../svg/play--filled.svg");
            colorize: white;
        }

        clicked => {
            buttonPressed(self.id);
        }

    }

    Button {
        button-color: #36548b;
        border-radius: 18px;
        text: "";
        id: "pause";
        font-size: 25px;

        Image {
            source: @image-url("../svg/pause--outline--filled.svg");
            colorize: white;
        }

        clicked => {
            buttonPressed(self.id);
        }

    }

}