import { Button } from "../generic/button.slint";

export component TitleBar inherits HorizontalLayout{

    callback buttonPressed(string);
    
    alignment: space-between;

        Text {

            horizontal-alignment: left;
            vertical-alignment: top;

            text: "Flow";
            font-size: 65px;
        }

        Button {

            width: 30%;

            id: "settings";

            button-color: #36548b;
            border-radius: 18px;
            
            Image {
                source: @image-url("../svg/settings.svg");
                colorize: white;
            }

            clicked => {
                buttonPressed(self.id);
            }

        }

}