export component Button inherits Rectangle {

    in property <color> button-color;
    in property <string> text;
    in property <length> font-size;
    in-out property <string> id: "";

    callback clicked;
    
    clip:  true;
    
    area := TouchArea {
        clicked => {
            clicked();
        }
    }

    Text {
        text: root.text;
        font-size: font-size;
    }

    function background-color() -> color {
        if (area.pressed) {
            return button-color.darker(25%);
        } else if (area.has-hover) {
            return button-color.brighter(25%);
        } else {
            return button-color;
        }
    }

    background: background-color();

    @children
}

export component Preview inherits Window {
    VerticalLayout {
        padding: 15px;

        Button {
            button-color: red;
            border-radius: 15px;
        }
    }
}