import "font/CoffeCake.ttf";
import "font/ARCO.ttf";
import "font/Super Foods.ttf";

import { Button } from "generic/button.slint";
import { ControlBar } from "modules/controlbar.slint";
import { TitleBar } from "modules/titlebar.slint";

export component Application inherits Window {

    callback buttonPressed(string);

    property <bool> showDebug: true;

    default-font-family: "Super Foods";

    min-width: 300px;
    min-height: 300px;

    preferred-width: 600px;
    preferred-height: 450px;

    background: #5583a8;

    verticalLayout := VerticalLayout {

        alignment: space-between;

        padding: 15px;

        TitleBar {
            height: 15%;

            buttonPressed(id) => {
                buttonPressed(id);
            }
        }

        Text {

            horizontal-alignment: center;

            text: "25:00";
            font-size: 70px;
        }
        
        ControlBar {
            height: 20%;

            buttonPressed(id) => {
                buttonPressed(id);
            }
        }

    }

}